// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElContainner: typeof import('element-plus/es')['ElContainner']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SideBarFiles: typeof import('./src/components/SideBar/SideBarFiles.vue')['default']
    SideBarSearch: typeof import('./src/components/SideBar/SideBarSearch.vue')['default']
    SideBarTOCTree: typeof import('./src/components/SideBar/SideBarTOCTree.vue')['default']
  }
}
