// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    SideBarFiles: typeof import('./components/SideBar/SideBarFiles.vue')['default']
    SideBarSearch: typeof import('./components/SideBar/SideBarSearch.vue')['default']
    SideBarTOCTree: typeof import('./components/SideBar/SideBarTOCTree.vue')['default']
  }
}
